#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.admin_username = "john"
    args.admin_name = "john"
    args.admin_email = "admin@example.com"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    #test_upgrade_from.dfcde24cce4db0527465acbc16dcecf9a3082858.name = "2.1.16"
