test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------
    
    args.username = "john"
    args.name = "john"
    args.email = "admin@example.com"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------
    
    test_upgrade_from.dfcde24cce4db0527465acbc16dcecf9a3082858.name = "Upgrade from 2.1.16"
